### ISSUE TITLE
Support for FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by b-d-m-p** [spamwax/alfred-pinboard#11]
Amazing workflow. Would you mind adding support for FirefoxDeveloperEdition? 

Thanks!

**Comment by spamwax** [comment]
I'll take a look, but meanwhile can you please describe the behavior of the workflow with FirefoxDeveloperEdition? any error messages? anything from the debug mode in Alfred will also be helpful.

**Comment by b-d-m-p** [comment]
I'm not sure how to debug it, but if you give me some guidance, I can do
it.

As for errors, everything appeared normal, but the notification said
"missing url" or something similar.
