### ISSUE TITLE
Possibility of having PU run after adding a link.

### ISSUE THREAD

**Issue by b-d-m-p** [spamwax/alfred-pinboard#12]
This may be a daft question, but would it not be possible to have pu run after adding a link automatically, so you wouldn't have to run it manually?

A lot of times, I add a link and then want to access it right away, then I can't find it and remember I need to run pu. It works, but I find I am doing it a lot.

Let me know what you think.

Cheers

**Comment by spamwax** [comment]
please check the settings, this feature is already available.

**Comment by b-d-m-p** [comment]
Sorry about that. Thanks.
