### ISSUE TITLE
Support for "to read" bookmarks

### ISSUE THREAD

**Issue by heliostatic** [spamwax/alfred-pinboard#13]
It would be great to be able to set the "to read" boolean on bookmarks.

**Comment by spamwax** [comment]
Adding _"toread"_ to description (i.e. after `;` within Alfred) will set the _toread_ boolean on bookmark now. commit: https://github.com/spamwax/alfred-pinboard/commit/d81d31c1f198fc6a2e9714e29a543ed7773c3587
