### ISSUE TITLE
feature requests - text full search

### ISSUE THREAD

**Issue by avshyz** [spamwax/alfred-pinboard#25]
Hi!
Given pinboard support full-text search on your bookmarks, I wondered if it'd be possible to add a command (pst perhaps?) uses that option

**Comment by spamwax** [comment]
what do you mean by full-text? and which Pinboard's API you are referring to?
Right now you can enable searching all of tags, title, description and url of your bookmarks.

**Comment by avshyz** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/3249081/86544108-efbf9d80-bf2c-11ea-877b-87e5d2f741a7.png">
Well, when you tick that checkbox there, it actually searches on the content of the page which is highly useful! 
I'm not sure if that functionality is exposed via a public api, but if it is - I'd be super helpful!

**Comment by spamwax** [comment]
that functionality is not exposed in API as far as I can tell: https://pinboard.in/api/
