### ISSUE TITLE
`p` command requires all browsers, not just the chosen one

### ISSUE THREAD

**Issue by bachya** [spamwax/alfred-pinboard#6]
Although I've chosen Chrome as my default browser, I receive the following message every time I try to save a tag:

![screen shot 2014-12-18 at 10 05 47 am](https://cloud.githubusercontent.com/assets/47216/5492287/7c479b64-869d-11e4-8316-59ed86a56daf.png)

I can cancel out of this dialog box; the pin still saves, but whatever is presumably supposed to happen in Chrome doesn't happen.

In my mind, I shouldn't be prompted for the location of browsers that I'm not using.

**Comment by spamwax** [comment]
@bachya This should be fixed now.
